#ifndef BOARD_AXIS_H
#define BOARD_AXIS_H

/**
 * AXI-Stream FIFO Hardware Abstraction Layer for MicroBlaze.
 *
 * Maps the Xilinx AXI4-Stream FIFO (axi_fifo_mm_s) register interface:
 *   TX channel: TDFD (data write) at +0x00, TDFV (vacancy) at +0x04
 *   RX channel: RDFD (data read)  at +0x00, RDFO (occupancy) at +0x04
 *
 * Base addresses come from xparameters.h (generated by Vitis from the
 * hardware design). Override AXIS_TX_FIFO_BASEADDR / AXIS_RX_FIFO_BASEADDR
 * if a different mapping is needed.
 */

#include <stdint.h>
#include <string.h>

/* ---- FIFO register offsets (in bytes) ---- */
#define AXIS_FIFO_TDFD   0x00   /* Transmit Data FIFO Data          (write) */
#define AXIS_FIFO_TDFV   0x04   /* Transmit Data FIFO Vacancy       (read)  */
#define AXIS_FIFO_RDFD   0x00   /* Receive  Data FIFO Data          (read)  */
#define AXIS_FIFO_RDFO   0x04   /* Receive  Data FIFO Occupancy     (read)  */
#define AXIS_FIFO_SRR    0x10   /* Software Reset Register                   */
#define AXIS_FIFO_TDFR   0x00   /* Transmit Data FIFO Reset  (write 1 to SRR) */

/* ---- Default base addresses (override via -D or xparameters.h) ---- */
#ifndef AXIS_TX_FIFO_BASEADDR
#ifdef XPAR_AXI_FIFO_MM_S_0_TX_BASEADDR
#define AXIS_TX_FIFO_BASEADDR  XPAR_AXI_FIFO_MM_S_0_TX_BASEADDR
#else
#define AXIS_TX_FIFO_BASEADDR  0x44A00000
#endif
#endif

#ifndef AXIS_RX_FIFO_BASEADDR
#ifdef XPAR_AXI_FIFO_MM_S_0_RX_BASEADDR
#define AXIS_RX_FIFO_BASEADDR  XPAR_AXI_FIFO_MM_S_0_RX_BASEADDR
#else
#define AXIS_RX_FIFO_BASEADDR  0x44A10000
#endif
#endif

/* ---- Platform-specific register I/O ---- */
#ifdef __MICROBLAZE__

#include "xil_io.h"

static inline void  axis_reg_write(uintptr_t addr, uint32_t val) { Xil_Out32(addr, val); }
static inline uint32_t axis_reg_read(uintptr_t addr)             { return Xil_In32(addr); }

#else /* host-side emulation / compile test */

/* When building on a host (Linux), stub out the hardware access.
 * Link against a real emulation backend if host-side testing is needed. */
#include <stdio.h>
static inline void  axis_reg_write(uintptr_t addr, uint32_t val) {
    (void)addr; (void)val;
}
static inline uint32_t axis_reg_read(uintptr_t addr) {
    (void)addr;
    return 0xFFFFFFFF;  /* all-ones = FIFO not ready on emulated read */
}

#endif /* __MICROBLAZE__ */

/* ---- FIFO status queries ---- */
static inline uint32_t axis_tx_vacancy(uintptr_t base) {
    return axis_reg_read(base + AXIS_FIFO_TDFV);
}

static inline uint32_t axis_rx_occupancy(uintptr_t base) {
    return axis_reg_read(base + AXIS_FIFO_RDFO);
}

/* ---- FIFO data I/O ---- */
static inline void axis_fifo_put(uintptr_t base, uint32_t word) {
    axis_reg_write(base + AXIS_FIFO_TDFD, word);
}

static inline uint32_t axis_fifo_get(uintptr_t base) {
    return axis_reg_read(base + AXIS_FIFO_RDFD);
}

/* ---- Blocking send / recv of byte buffers over AXI-Stream FIFOs ---- */

/**
 * Write `size` bytes from `data` to the TX FIFO in 32-bit words.
 * Blocks while FIFO is full.  `size` should be a multiple of 4.
 * Returns 0 on success, non-zero on timeout (if implemented).
 */
static inline int axis_fifo_send(uintptr_t tx_base, const void* data, unsigned int size) {
    const uint32_t* words = (const uint32_t*)data;
    unsigned int count = size / 4;

    for (unsigned int i = 0; i < count; i++) {
        /* spin while FIFO full (vacancy == 0) */
        while (axis_tx_vacancy(tx_base) == 0) { }
        axis_fifo_put(tx_base, words[i]);
    }

    /* trailing bytes (if size not word-aligned) — pad to word */
    unsigned int rem = size % 4;
    if (rem) {
        uint32_t last = 0;
        memcpy(&last, (const uint8_t*)data + (count * 4), rem);
        while (axis_tx_vacancy(tx_base) == 0) { }
        axis_fifo_put(tx_base, last);
    }
    return 0;
}

/**
 * Read `size` bytes from the RX FIFO into `buf` in 32-bit words.
 * Blocks while FIFO is empty.  `size` should be a multiple of 4.
 * Returns the number of bytes actually read.
 */
static inline int axis_fifo_recv(uintptr_t rx_base, void* buf, unsigned int size) {
    uint32_t* words = (uint32_t*)buf;
    unsigned int count = size / 4;

    for (unsigned int i = 0; i < count; i++) {
        /* spin while FIFO empty (occupancy == 0) */
        while (axis_rx_occupancy(rx_base) == 0) { }
        words[i] = axis_fifo_get(rx_base);
    }

    /* trailing bytes — read the word but only copy the needed bytes */
    unsigned int rem = size % 4;
    if (rem) {
        while (axis_rx_occupancy(rx_base) == 0) { }
        uint32_t last = axis_fifo_get(rx_base);
        memcpy((uint8_t*)buf + (count * 4), &last, rem);
    }
    return (int)size;
}

#endif /* BOARD_AXIS_H */
